GeneralEducationRequirement.create("requirement"=> "FINE ARTS ELECTIVE", "course" => "ARCH 1003")
GeneralEducationRequirement.create("requirement"=> "FINE ARTS ELECTIVE", "course" => "ARHS 1003")
GeneralEducationRequirement.create("requirement"=> "FINE ARTS ELECTIVE", "course" => "COMM 1003")
GeneralEducationRequirement.create("requirement"=> "FINE ARTS ELECTIVE", "course" => "DANC 1003")
GeneralEducationRequirement.create("requirement"=> "FINE ARTS ELECTIVE", "course" => "DRAM 1003")
GeneralEducationRequirement.create("requirement"=> "FINE ARTS ELECTIVE", "course" => "LARC 1003")
GeneralEducationRequirement.create("requirement"=> "FINE ARTS ELECTIVE", "course" => "MLIT 1003")
GeneralEducationRequirement.create("requirement"=> "HISTORY/GOVERNMENT ELECTIVE", "course"=>"HIST 2003")
GeneralEducationRequirement.create("requirement"=> "HISTORY/GOVERNMENT ELECTIVE", "course"=>"HIST 2013")
GeneralEducationRequirement.create("requirement"=> "HISTORY/GOVERNMENT ELECTIVE", "course"=>"PLSC 2003")
GeneralEducationRequirement.create("requirement"=> "SOCIAL SCIENCE ELECTIVE", "course"=>"AGEC 1103")
GeneralEducationRequirement.create("requirement"=> "SOCIAL SCIENCE ELECTIVE", "course"=>"AGEC 2103")
GeneralEducationRequirement.create("requirement"=> "SOCIAL SCIENCE ELECTIVE", "course"=>"ANTH 1023")
GeneralEducationRequirement.create("requirement"=> "SOCIAL SCIENCE ELECTIVE", "course"=>"ECON 2013")
GeneralEducationRequirement.create("requirement"=> "SOCIAL SCIENCE ELECTIVE", "course"=>"ECON 2023")
GeneralEducationRequirement.create("requirement"=> "SOCIAL SCIENCE ELECTIVE", "course"=>"ECON 2143")
GeneralEducationRequirement.create("requirement"=> "SOCIAL SCIENCE ELECTIVE", "course"=>"GEOG 1123")
GeneralEducationRequirement.create("requirement"=> "SOCIAL SCIENCE ELECTIVE", "course"=>"GEOG 2003")
GeneralEducationRequirement.create("requirement"=> "SOCIAL SCIENCE ELECTIVE", "course"=>"HESC 1403")
GeneralEducationRequirement.create("requirement"=> "SOCIAL SCIENCE ELECTIVE", "course"=>"HESC 2413")
GeneralEducationRequirement.create("requirement"=> "SOCIAL SCIENCE ELECTIVE", "course"=>"HIST 1113")
GeneralEducationRequirement.create("requirement"=> "SOCIAL SCIENCE ELECTIVE", "course"=>"HIST 1123")
GeneralEducationRequirement.create("requirement"=> "SOCIAL SCIENCE ELECTIVE", "course"=>"HIST 2003")
GeneralEducationRequirement.create("requirement"=> "SOCIAL SCIENCE ELECTIVE", "course"=>"HIST 2013")
GeneralEducationRequirement.create("requirement"=> "SOCIAL SCIENCE ELECTIVE", "course"=>"HUMN 1114H")
GeneralEducationRequirement.create("requirement"=> "SOCIAL SCIENCE ELECTIVE", "course"=>"HUMN 2114H")
GeneralEducationRequirement.create("requirement"=> "SOCIAL SCIENCE ELECTIVE", "course"=>"PLSC 2003")
GeneralEducationRequirement.create("requirement"=> "SOCIAL SCIENCE ELECTIVE", "course"=>"PLSC 2013")
GeneralEducationRequirement.create("requirement"=> "SOCIAL SCIENCE ELECTIVE", "course"=>"PLSC 2203")
GeneralEducationRequirement.create("requirement"=> "SOCIAL SCIENCE ELECTIVE", "course"=>"PSYC 2003")
GeneralEducationRequirement.create("requirement"=> "SOCIAL SCIENCE ELECTIVE", "course"=>"RESM 2853")
GeneralEducationRequirement.create("requirement"=> "SOCIAL SCIENCE ELECTIVE", "course"=>"RSOC 2603")
GeneralEducationRequirement.create("requirement"=> "SOCIAL SCIENCE ELECTIVE", "course"=>"SOCI 2013")
GeneralEducationRequirement.create("requirement"=> "SOCIAL SCIENCE ELECTIVE", "course"=>"SOCI 2033")
GeneralEducationRequirement.create("requirement"=> "BASIC SCIENCE ELECTIVE WITH LAB", "course"=>"ASTR 2003")
GeneralEducationRequirement.create("requirement"=> "BASIC SCIENCE ELECTIVE WITH LAB", "course"=>"BIOL 1543")
GeneralEducationRequirement.create("requirement"=> "BASIC SCIENCE ELECTIVE WITH LAB", "course"=>"ENSC 1003")
GeneralEducationRequirement.create("requirement"=> "BASIC SCIENCE ELECTIVE WITH LAB", "course"=>"GEOL 1113")
GeneralEducationRequirement.create("requirement"=> "BASIC SCIENCE ELECTIVE WITH LAB", "course"=>"BIOL 1603")
GeneralEducationRequirement.create("requirement"=> "BASIC SCIENCE ELECTIVE WITH LAB", "course"=>"BIOL 2213")
GeneralEducationRequirement.create("requirement"=> "BASIC SCIENCE ELECTIVE WITH LAB", "course"=>"CHEM 1133")
GeneralEducationRequirement.create("requirement"=> "BASIC SCIENCE ELECTIVE WITH LAB", "course"=>"PHYS 3614")
GeneralEducationRequirement.create("requirement"=> "FRESHMAN SCIENCE ELECTIVE", "course"=>"PHYS 2074")
GeneralEducationRequirement.create("requirement"=> "FRESHMAN SCIENCE ELECTIVE", "course"=>"CHEM 1133")
