Major.create({"major"=>"computer engineering"})
Major.create({"major"=>"computer science (bs)"})
Major.create({"major"=>"computer science (ba)"})
Major.create({"major"=>"computer engineering", "course"=>"GNEG 1111", "year"=>"1", "semester"=>"Fall"})
Major.create({"major"=>"computer engineering", "course"=>"MATH 2554", "year"=>"1", "semester"=>"Fall"})
Major.create({"major"=>"computer engineering", "course"=>"CHEM 1113", "year"=>"1", "semester"=>"Fall"})
Major.create({"major"=>"computer engineering", "course"=>"PHYS 2054", "year"=>"1", "semester"=>"Fall"})
Major.create({"major"=>"computer engineering", "course"=>"PHYS 2054", "year"=>"1", "semester"=>"Fall"})
Major.create({"major"=>"computer engineering", "course"=>"ENGL 1013", "year"=>"1", "semester"=>"Fall"})
Major.create({"major"=>"computer engineering", "course"=>"FRESHMAN SCIENCE ELECTIVE", "year"=>"1", "semester"=>"Spring"})
Major.create({"major"=>"computer engineering", "course"=>"HISTORY/GOVERNMENT ELECTIVE", "year"=>"1", "semester"=>"Spring"})
Major.create({"major"=>"computer engineering", "course"=>"ENGL 1023", "year"=>"1", "semester"=>"Spring"})
Major.create({"major"=>"computer engineering", "course"=>"CSCE 2004", "year"=>"2", "semester"=>"Fall"})
Major.create({"major"=>"computer engineering", "course"=>"CSCE 2114", "year"=>"2", "semester"=>"Fall"})
Major.create({"major"=>"computer engineering", "course"=>"MATH 2574", "year"=>"2", "semester"=>"Fall"})
Major.create({"major"=>"computer engineering", "course"=>"MATH 2603", "year"=>"2", "semester"=>"Fall"})
Major.create({"major"=>"computer engineering", "course"=>"CSCE 2014", "year"=>"2", "semester"=>"Spring"})
Major.create({"major"=>"computer engineering", "course"=>"CSCE 2214", "year"=>"2", "semester"=>"Spring"})
Major.create({"major"=>"computer engineering", "course"=>"MATH 2584", "year"=>"2", "semester"=>"Spring"})Major.create({"major"=>"computer engineering", "course"=>"SOCIAL SCIENCE ELECTIVE", "year"=>"2", "semester"=>"Spring"})
Major.create({"major"=>"computer engineering", "course"=>"SOCIAL SCIENCE ELECTIVE", "year"=>"2", "semester"=>"Spring"})
Major.create({"major"=>"computer engineering", "course"=>"CSCE 3193", "year"=>"3", "semester"=>"Fall"})
Major.create({"major"=>"computer engineering", "course"=>"CSCE 3953", "year"=>"3", "semester"=>"Fall"})
Major.create({"major"=>"computer engineering", "course"=>"PHIL 3103", "year"=>"3", "semester"=>"Fall"})
Major.create({"major"=>"computer engineering", "course"=>"COMM 1313", "year"=>"3", "semester"=>"Fall"})
Major.create({"major"=>"computer engineering", "course"=>"BASIC SCIENCE ELECTIVE WITH LAB", "year"=>"3", "semester"=>"Fall"})
Major.create({"major"=>"computer engineering", "course"=>"CSCE 3513", "year"=>"3", "semester"=>"Spring"})
Major.create({"major"=>"computer engineering", "course"=>"CSCE 3613", "year"=>"3", "semester"=>"Spring"})
Major.create({"major"=>"computer engineering", "course"=>"ELEG 3933", "year"=>"3", "semester"=>"Spring"})
Major.create({"major"=>"computer engineering", "course"=>"FREE ELECTIVE", "year"=>"3", "semester"=>"Spring"})
Major.create({"major"=>"computer engineering", "course"=>"STAT 3013", "year"=>"3", "semester"=>"Spring"})Major.create({"major"=>"computer engineering", "course"=>"CSCE 4561", "year"=>"4", "semester"=>"Fall"})
Major.create({"major"=>"computer engineering", "course"=>"CSCE 4114", "year"=>"4", "semester"=>"Fall"})
Major.create({"major"=>"computer engineering", "course"=>"CSCE ELECTIVE", "year"=>"4", "semester"=>"Fall"})
Major.create({"major"=>"computer engineering", "course"=>"CSCE ELECTIVE", "year"=>"4", "semester"=>"Fall"})
Major.create({"major"=>"computer engineering", "course"=>"FINE ARTS ELECTIVE", "year"=>"4", "semester"=>"Fall"})
Major.create({"major"=>"computer engineering", "course"=>"FREE ELECTIVE", "year"=>"4", "semester"=>"Fall"})
Major.create({"major"=>"computer engineering", "course"=>"CSCE 4213", "year"=>"4", "semester"=>"Spring"})
Major.create({"major"=>"computer engineering", "course"=>"CSCE 4963", "year"=>"4", "semester"=>"Spring"})
Major.create({"major"=>"computer engineering", "course"=>"CSCE ELECTIVE", "year"=>"4", "semester"=>"Spring"})
Major.create({"major"=>"computer engineering", "course"=>"CSCE ELECTIVE", "year"=>"4", "semester"=>"Spring"})
Major.create({"major"=>"computer engineering", "course"=>"SOCIAL SCIENCE ELECTIVE", "year"=>"4", "semester"=>"Spring"})
Major.create({"major"=>"computer science (ba)", "course"=>"ENGL 1013", "year"=>"1", "semester"=>"Fall"})
Major.create({"major"=>"computer science (ba)", "course"=>"MATH 2554", "year"=>"1", "semester"=>"Fall"})
Major.create({"major"=>"computer science (ba)", "course"=>"SOCIAL SCIENCE ELECTIVE", "year"=>"1", "semester"=>"Fall"})
Major.create({"major"=>"computer science (ba)", "course"=>"HISTORY/GOVERNMENT ELECTIVE", "year"=>"1", "semester"=>"Fall"})
Major.create({"major"=>"computer science (ba)", "course"=>"CSCE 2004", "year"=>"1", "semester"=>"Spring"})
Major.create({"major"=>"computer science (ba)", "course"=>"CSCE 2114", "year"=>"1", "semester"=>"Spring"})
Major.create({"major"=>"computer science (ba)", "course"=>"ENGL 1023", "year"=>"1", "semester"=>"Spring"})
Major.create({"major"=>"computer science (ba)", "course"=>"MATH 2603C", "year"=>"1", "semester"=>"Spring"})
Major.create({"major"=>"computer science (ba)", "course"=>"CSCE 2014", "year"=>"2", "semester"=>"Fall"})
Major.create({"major"=>"computer science (ba)", "course"=>"CSCE 2214", "year"=>"2", "semester"=>"Fall"})
Major.create({"major"=>"computer science (ba)", "course"=>"SOCIAL SCIENCE ELECTIVE", "year"=>"2", "semester"=>"Fall"})
Major.create({"major"=>"computer science (ba)", "course"=>"FINE ARTS", "year"=>"2", "semester"=>"Fall"})
Major.create({"major"=>"computer science (ba)", "course"=>"FREE ELECTIVE", "year"=>"2", "semester"=>"Fall"})
Major.create({"major"=>"computer science (ba)", "course"=>"CSCE 3193", "year"=>"2", "semester"=>"Spring"})
Major.create({"major"=>"computer science (ba)", "course"=>"COMM 1313", "year"=>"2", "semester"=>"Spring"})
Major.create({"major"=>"computer science (ba)", "course"=>"STAT 2303", "year"=>"2", "semester"=>"Spring"})
Major.create({"major"=>"computer science (ba)", "course"=>"CSCE ELECTIVE", "year"=>"3", "semester"=>"Fall"})
Major.create({"major"=>"computer science (ba)", "course"=>"ENGL 3053", "year"=>"3", "semester"=>"Fall"})
Major.create({"major"=>"computer science (ba)", "course"=>"SCIENCE ELECTIVE", "year"=>"3", "semester"=>"Fall"})
Major.create({"major"=>"computer science (ba)", "course"=>"FREE ELECTIVE", "year"=>"3", "semester"=>"Fall"})
Major.create({"major"=>"computer science (ba)", "course"=>"FREE ELECTIVE", "year"=>"3", "semester"=>"Fall"})
Major.create({"major"=>"computer science (ba)", "course"=>"CSCE ELECTIVE", "year"=>"3", "semester"=>"Spring"})
Major.create({"major"=>"computer science (ba)", "course"=>"PHIL 3103", "year"=>"3", "semester"=>"Spring"})
Major.create({"major"=>"computer science (ba)", "course"=>"SOCIAL SCIENCE ELECTIVE", "year"=>"3", "semester"=>"Spring"})
Major.create({"major"=>"computer science (ba)", "course"=>"FREE ELECTIVE", "year"=>"3", "semester"=>"Spring"})
Major.create({"major"=>"computer science (ba)", "course"=>"FREE ELECTIVE", "year"=>"3", "semester"=>"Spring"})
Major.create({"major"=>"computer science (ba)", "course"=>"CSCE ELECTIVES", "year"=>"4", "semester"=>"Fall"})
Major.create({"major"=>"computer science (ba)", "course"=>"CSCE ELECTIVE", "year"=>"4", "semester"=>"Fall"})
Major.create({"major"=>"computer science (ba)", "course"=>"SCIENCE ELECTIVE", "year"=>"4", "semester"=>"Fall"})
Major.create({"major"=>"computer science (ba)", "course"=>"FREE ELECTIVE", "year"=>"4", "semester"=>"Fall"})
Major.create({"major"=>"computer science (ba)", "course"=>"FREE ELECTIVE", "year"=>"4", "semester"=>"Fall"})
Major.create({"major"=>"computer science (ba)", "course"=>"CSCE ELECTIVE", "year"=>"4", "semester"=>"Spring"})
Major.create({"major"=>"computer science (ba)", "course"=>"CSCE ELECTIVE", "year"=>"4", "semester"=>"Spring"})
Major.create({"major"=>"computer science (ba)", "course"=>"FREE ELECTIVE", "year"=>"4", "semester"=>"Spring"})
Major.create({"major"=>"computer science (ba)", "course"=>"FREE ELECTIVE", "year"=>"4", "semester"=>"Spring"})
Major.create({"major"=>"computer science (ba)", "course"=>"FREE ELECTIVE", "year"=>"4", "semester"=>"Spring"})Major.create({"major"=>"computer science (bs)", "course"=>"GNEG 1111", "year"=>"1", "semester"=>"Fall"})
Major.create({"major"=>"computer science (bs)", "course"=>"GNEG 1111", "year"=>"1", "semester"=>"Fall"})
Major.create({"major"=>"computer science (bs)", "course"=>"CHEM 1113", "year"=>"1", "semester"=>"Fall"})
Major.create({"major"=>"computer science (bs)", "course"=>"ENGL 1013", "year"=>"1", "semester"=>"Fall"})
Major.create({"major"=>"computer science (bs)", "course"=>"MATH 2554", "year"=>"1", "semester"=>"Fall"})
Major.create({"major"=>"computer science (bs)", "course"=>"PHYS 2054", "year"=>"1", "semester"=>"Fall"})
Major.create({"major"=>"computer science (bs)", "course"=>"GNEG 1121", "year"=>"1", "semester"=>"Spring"})
Major.create({"major"=>"computer science (bs)", "course"=>"MATH 2564", "year"=>"1", "semester"=>"Spring"})
Major.create({"major"=>"computer science (bs)", "course"=>"FRESHMAN SCIENCE ELECTIVE", "year"=>"1", "semester"=>"Spring"})
Major.create({"major"=>"computer science (bs)", "course"=>"ENGL 1023", "year"=>"1", "semester"=>"Spring"})
Major.create({"major"=>"computer science (bs)", "course"=>"HISTORY/GOVERNMENT ELECTIVE", "year"=>"1", "semester"=>"Spring"})
Major.create({"major"=>"computer science (bs)", "course"=>"CSCE 2004", "year"=>"2", "semester"=>"Fall"})
Major.create({"major"=>"computer science (bs)", "course"=>"CSCE 2114", "year"=>"2", "semester"=>"Fall"})
Major.create({"major"=>"computer science (bs)", "course"=>"MATH 2603", "year"=>"2", "semester"=>"Fall"})
Major.create({"major"=>"computer science (bs)", "course"=>"BASIC SCIENCE ELECTIVE WITH LAB", "year"=>"2", "semester"=>"Fall"})
Major.create({"major"=>"computer science (bs)", "course"=>"SOCIAL SCIENCE ELECTIVE", "year"=>"2", "semester"=>"Fall"})
Major.create({"major"=>"computer science (bs)", "course"=>"CSCE 2014", "year"=>"2", "semester"=>"Spring"})
Major.create({"major"=>"computer science (bs)", "course"=>"CSCE 2214", "year"=>"2", "semester"=>"Spring"})
Major.create({"major"=>"computer science (bs)", "course"=>"MATH 3103", "year"=>"2", "semester"=>"Spring"})
Major.create({"major"=>"computer science (bs)", "course"=>"FINE ARTS ELECTIVE", "year"=>"2", "semester"=>"Spring"})
Major.create({"major"=>"computer science (bs)", "course"=>"SOCIAL SCIENCE ELECTIVE", "year"=>"2", "semester"=>"Spring"})
Major.create({"major"=>"computer science (bs)", "course"=>"CSCE 3193", "year"=>"3", "semester"=>"Spring"})
Major.create({"major"=>"computer science (bs)", "course"=>"CSCE 3313", "year"=>"3", "semester"=>"Spring"})
Major.create({"major"=>"computer science (bs)", "course"=>"COMM 1313", "year"=>"3", "semester"=>"Spring"})
Major.create({"major"=>"computer science (bs)", "course"=>"MATH 2083", "year"=>"3", "semester"=>"Spring"})
Major.create({"major"=>"computer science (bs)", "course"=>"PHIL 3103", "year"=>"3", "semester"=>"Spring"})
Major.create({"major"=>"computer science (bs)", "course"=>"CSCE 3513", "year"=>"3", "semester"=>"Spring"})
Major.create({"major"=>"computer science (bs)", "course"=>"CSCE 3613", "year"=>"3", "semester"=>"Spring"})
Major.create({"major"=>"computer science (bs)", "course"=>"FREE ELECTIVE", "year"=>"3", "semester"=>"Spring"})
Major.create({"major"=>"computer science (bs)", "course"=>"STAT 3013", "year"=>"3", "semester"=>"Spring"})
Major.create({"major"=>"computer science (bs)", "course"=>"SOCIAL SCIENCE ELECTIVE", "year"=>"3", "semester"=>"Spring"})
Major.create({"major"=>"computer science (bs)", "course"=>"CSCE 4523", "year"=>"4", "semester"=>"Fall"})
Major.create({"major"=>"computer science (bs)", "course"=>"CSCE 4561", "year"=>"4", "semester"=>"Fall"})
Major.create({"major"=>"computer science (bs)", "course"=>"CSCE ELECTIVE", "year"=>"4", "semester"=>"Fall"})
Major.create({"major"=>"computer science (bs)", "course"=>"ELECTIVE", "year"=>"4", "semester"=>"Fall"})
Major.create({"major"=>"computer science (bs)", "course"=>"CSCE ELECTIVE", "year"=>"4", "semester"=>"Fall"})
Major.create({"major"=>"computer science (bs)", "course"=>"CSCE 4323", "year"=>"4", "semester"=>"Spring"})
Major.create({"major"=>"computer science (bs)", "course"=>"CSCE 4963", "year"=>"4", "semester"=>"Spring"})
Major.create({"major"=>"computer science (bs)", "course"=>"CSCE ELECTIVE", "year"=>"4", "semester"=>"Spring"})
Major.create({"major"=>"computer science (bs)", "course"=>"FREE ELECTIVE", "year"=>"4", "semester"=>"Spring"})
Major.create({"major"=>"computer science (bs)", "course"=>"FREE ELECTIVE", "year"=>"4", "semester"=>"Spring"})