Major.new({"major"=>"csce"})
Major.new({"major"=>"csce", "course"=>"CSCE 2114", "year"=>"0", "semester"=>"Fall"})
Major.find(2).update({"course"=>"CSCE 2114", "year"=>"0", "semester"=>"Spring"})
Major.find(2).update({"course"=>"CSCE 2114", "year"=>"0", "semester"=>"Summer"})
Major.new({"major"=>"csce", "course"=>"CSCE 2004", "year"=>"0", "semester"=>"Fall"})
Major.find(1219).update({"course"=>"GNEG 1111", "year"=>"1", "semester"=>"Fall"})
Major.find(1219).update({"course"=>"GNEG 1111", "year"=>"1", "semester"=>"Fall"})
Major.find(1219).update({"course"=>"GNEG 1111", "year"=>"1", "semester"=>"Fall"})
Major.find(1219).update({"course"=>"GNEG 1111", "year"=>"1", "semester"=>"Fall"})
Major.find(1219).update({"course"=>"GNEG 1111", "year"=>"1", "semester"=>"Fall"})
Major.find(1219).update({"course"=>"GNEG 1111", "year"=>"1", "semester"=>"Fall"})
Major.find(1219).update({"course"=>"GNEG 1111", "year"=>"1", "semester"=>"Fall"})
Major.new({"major"=>"computer science and computer engineering", "course"=>"", "year"=>""})
Major.new({"major"=>"computer science and computer engineering", "course"=>"", "year"=>""})
Major.new({"major"=>"computer science and computer engineering", "course"=>"", "year"=>""})
Major.new({"major"=>"computer science and computer engineering", "course"=>"", "year"=>""})
Major.new({"major"=>"computer science and computer engineering", "course"=>"", "year"=>""})
