Major.new({"major"=>"csce"})
Major.new({"major"=>"csce", "course"=>"CSCE 2114", "year"=>"0", "semester"=>"Fall"})
Major.find(2).update({"course"=>"CSCE 2114", "year"=>"0", "semester"=>"Spring"})
Major.find(2).update({"course"=>"CSCE 2114", "year"=>"0", "semester"=>"Summer"})
Major.new({"major"=>"csce", "course"=>"CSCE 2004", "year"=>"0", "semester"=>"Fall"})
Major.new({"major"=>"csce", "course"=>"CSCE 2014", "year"=>"1", "semester"=>"Fall"})
Major.new({"major"=>"accounting"})
Major.new({"major"=>"accounting"})
Major.new({"major"=>"accounting", "course"=>"ACCT 2013", "year"=>"1", "semester"=>"Fall"})
Major.new({"major"=>"accounting", "course"=>"WCOB 1023", "year"=>"1", "semester"=>"Fall"})
Major.find(7).update({"course"=>"CSCE 1953", "year"=>"1", "semester"=>"Fall"})
